# Generated by Django 3.2 on 2021-04-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rating',
            new_name='rated',
        ),
    ]
