# Generated by Django 3.2 on 2021-04-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210421_1629'),
        ('main_app', '0006_auto_20210421_2109'),
    ]

    operations = [
    ]
